# Generated by Django 2.0.13 on 2020-06-15 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tsx_id', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('overall_design', models.TextField(blank=True, null=True, verbose_name='overall_design')),
                ('contributors', models.TextField(blank=True, null=True, verbose_name='contributors')),
                ('technologies', models.TextField(blank=True, null=True, verbose_name='technologies')),
                ('pubmed_id', models.TextField(blank=True, null=True, verbose_name='pubmed_ids')),
                ('cross_link', models.TextField(blank=True, null=True, verbose_name='cross_link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_study_created_by', to=settings.AUTH_USER_MODEL)),
                ('edit_groups', models.ManyToManyField(blank=True, related_name='edit_access_to', to='auth.Group')),
                ('read_groups', models.ManyToManyField(blank=True, related_name='read_access_to', to='auth.Group')),
            ],
            options={
                'permissions': (('view_study', 'View study'),),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
