# Generated by Django 2.0.13 on 2020-06-19 09:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20200619_0931'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genelists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('default_conversion', 'Single column with gene ID'), ('file_conversion', 'Use a custom conversion file')], default='default_conversion', max_length=20)),
                ('format', models.CharField(choices=[('gene_id', 'Entrez gene ID'), ('locus_tag', 'Locus tag'), ('ensembl_id', 'Ensembl ID'), ('ensembl_transcript__contains', 'Ensembl transcript'), ('ensembl_protein__contains', 'Ensembl protein'), ('accession_transcript__contains', 'Accession transcript'), ('accession_protein__contains', 'Accession protein'), ('uniprot_id', 'Uniprot ID'), ('uniprot_accession', 'Uniprot accession')], default='gene_id', max_length=50)),
                ('file_type', models.CharField(choices=[('GEO', 'GEO conversion file'), ('CUSTOM', 'Custom conversion file')], default='CUSTOM', max_length=20)),
                ('geo_platform_id', models.CharField(blank=True, max_length=20, null=True)),
                ('conversion_file', models.FileField(blank=True, upload_to='gene_lists')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genelists_conversiontype_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='genelist',
            old_name='conversion_file',
            new_name='converted_file',
        ),
        migrations.AddField(
            model_name='genelist',
            name='conversion_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='genelist',
            name='converted_pickle_file',
            field=models.FileField(blank=True, upload_to='gene_lists'),
        ),
        migrations.AddField(
            model_name='genelist',
            name='raw_file',
            field=models.FileField(blank=True, upload_to='gene_lists'),
        ),
        migrations.AddField(
            model_name='genelist',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genelists', to='series.Serie'),
        ),
        migrations.AddField(
            model_name='genelist',
            name='status',
            field=models.CharField(choices=[('CONVERTED', 'Converted'), ('NO_CONVERSION', 'No conversion'), ('PENDING', 'Pending'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='genelist',
            name='type',
            field=models.CharField(choices=[('CONVERSION', 'Need a conversion'), ('NO_CONVERSION', 'No conversion needed'), ('OTHER', 'Bypass conversion')], default='CONVERSION', max_length=20),
        ),
        migrations.AddField(
            model_name='genelist',
            name='conversion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genelists', to='genelists.ConversionType'),
        ),
    ]
