# Generated by Django 2.0.13 on 2020-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelists', '0002_auto_20200619_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontype',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='genelist',
            old_name='organism',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='genelist',
            name='conversion_type',
        ),
        migrations.AddField(
            model_name='genelist',
            name='conversion_file',
            field=models.FileField(blank=True, upload_to='gene_lists'),
        ),
        migrations.AddField(
            model_name='genelist',
            name='format',
            field=models.CharField(choices=[('gene_id', 'Entrez gene ID'), ('locus_tag', 'Locus tag'), ('ensembl_id', 'Ensembl ID'), ('ensembl_transcript__contains', 'Ensembl transcript'), ('ensembl_protein__contains', 'Ensembl protein'), ('accession_transcript__contains', 'Accession transcript'), ('accession_protein__contains', 'Accession protein'), ('uniprot_id', 'Uniprot ID'), ('uniprot_accession', 'Uniprot accession')], default='gene_id', max_length=50),
        ),
        migrations.AddField(
            model_name='genelist',
            name='geo_platform_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genelist',
            name='type',
            field=models.CharField(choices=[('no_conversion', 'No conversion'), ('default_conversion', 'Single column with common gene format'), ('geo_file_conversion', 'Use a GEO conversion file'), ('file_conversion', 'Use a custom conversion file')], default='no_conversion', max_length=20),
        ),
        migrations.DeleteModel(
            name='ConversionType',
        ),
    ]
