# Generated by Django 2.0.13 on 2020-06-15 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tsx_id', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('overall_design', models.TextField(blank=True, null=True, verbose_name='overall_design')),
                ('contributors', models.TextField(blank=True, null=True, verbose_name='contributors')),
                ('pubmed_ids', models.TextField(blank=True, null=True, verbose_name='pubmed_ids')),
                ('cross_link', models.TextField(blank=True, null=True, verbose_name='cross_link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('ancestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subseries_full', to='series.Series')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_series_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subseries', to='series.Series')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='studies.Study')),
            ],
        ),
    ]
