# Generated by Django 2.0.13 on 2020-06-19 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0002_auto_20200619_0931'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tsx_id', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('overall_design', models.TextField(blank=True, null=True, verbose_name='overall_design')),
                ('contributors', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
                ('technologies', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
                ('pubmed_ids', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=None)),
                ('cross_links', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
                ('species', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user')),
                ('ancestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subseries_full', to='series.Serie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_serie_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subseries', to='series.Serie')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='studies.Study')),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='ancestor',
        ),
        migrations.RemoveField(
            model_name='series',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='series',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='series',
            name='study',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
