# Generated by Django 2.0.13 on 2020-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20200619_0931'),
        ('series', '0002_auto_20200619_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='series', to='platforms.Platform'),
        ),
    ]
