# Generated by Django 2.0.13 on 2020-06-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geneulike.platforms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('geo_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(choices=[('GEO', 'GEO based platform'), ('CUSTOM', 'Platform with custom conversion file')], default='GEO', max_length=100)),
                ('ftp', models.CharField(blank=True, max_length=200, null=True)),
                ('conversion_file', models.FileField(blank=True, upload_to=geneulike.platforms.models.get_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms_platform_created_by', to=settings.AUTH_USER_MODEL)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='species.Species')),
            ],
        ),
    ]
