# Generated by Django 2.0.13 on 2020-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='geo_accession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
