# Generated by Django 2.0.13 on 2020-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platform_geo_accession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='type',
        ),
        migrations.AddField(
            model_name='platform',
            name='download_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
