# Generated by Django 2.0.13 on 2020-06-12 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('locus_tag', models.CharField(blank=True, max_length=50)),
                ('synonyms', models.TextField(blank=True)),
                ('discontinued_gene_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('ensembl_id', models.CharField(blank=True, max_length=50)),
                ('ensembl_transcript', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('ensembl_protein', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('accession_transcript', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('accession_protein', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('uniprot_accession', models.CharField(blank=True, max_length=50)),
                ('uniprot_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
